
=========================================================================================================================== 

ERROR OCCURRED

DATE & TIME: 27-01-2018 1.04.51 PM
SOURCE: Microsoft.EntityFrameworkCore.Relational
METHOD: Void Execute(Microsoft.EntityFrameworkCore.Storage.IRelationalConnection)
ERROR: An error occurred while updating the entries. See the inner exception for details.
STACKTRACE:    at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.MySqlBatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IReadOnlyList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at PIT.BAL.Services.Dictonary.DictonaryService.Update(DictonaryModel obj) in E:\CSharpProgram\gitProject\PixInfotechProject\Dictionary\API\PIT.BAL\Services\Dictonary\DictonaryService.cs:line 173
